import { ChatSummary } from "@/features/chat/page-utils";
import { t } from "@/lib/locale";
import type { Dispatch, SetStateAction } from "react";
import { useEffect, useRef, useState } from "react";
import { chatApi } from "@/features/chat/api-client";
import { getChatPrefsStorageKey, loadAccountChatDefaults } from "@/features/chat/preferences";
import type { ChatScopedPreferences } from "@/features/chat/types";
import { COLLAPSED_CHAT_LIMIT, LAST_ACTIVE_CHAT_STORAGE_KEY } from "@/features/chat/types";

type Options = {
  activeChatId: string | null;
  setActiveChatId: Dispatch<SetStateAction<string | null>>;
  preferences: ChatScopedPreferences;
  applyChatPreferences: (preferences: ChatScopedPreferences) => void;
  resetConversation: () => void;
  persistCurrentStreamingAssistantIfNeeded: (chatId: string | null) => Promise<void>;
  setPageError: Dispatch<SetStateAction<string | null>>;
};
function isAutoGeneratedTitle(title: string | null | undefined): boolean {
  const normalized = (title ?? "").replace(/\s+/g, " ").trim().toLowerCase();
  if (!normalized) return true;
  // A placeholder title the server has already persisted for empty
  // conversations, so it is a data value to recognise, not copy to translate.
  return normalized === "new chat" || normalized === "新会话" || normalized === "untitled";
}
export function useConversations({ activeChatId, setActiveChatId, preferences, applyChatPreferences, resetConversation, persistCurrentStreamingAssistantIfNeeded, setPageError }: Options) {
  const { modelMode, selectedChatModel, selectedImageModel, selectedVideoModel, selectedManualTool, manualToolsOnly } = preferences;
  const [isLoadingChats, setIsLoadingChats] = useState(true);
  const [chats, setChats] = useState<ChatSummary[]>([]);
  const [isCreatingChat, setIsCreatingChat] = useState(false);
  const [editingChatId, setEditingChatId] = useState<string | null>(null);
  const [editingTitle, setEditingTitle] = useState("");
  const [isChatListExpanded, setIsChatListExpanded] = useState(false);
  const [isEphemeralSaving, setIsEphemeralSaving] = useState(false);
  const [documentTopics, setDocumentTopics] = useState<string[]>([]);
  const [nextChatsCursor, setNextChatsCursor] = useState<string | null>(null);
  const [isLoadingMoreChats, setIsLoadingMoreChats] = useState(false);
  const chatsRequestRef = useRef(0);
  const loadingMoreRef = useRef(false);
  const activeIdRef = useRef(activeChatId);
  useEffect(() => { activeIdRef.current = activeChatId; }, [activeChatId]);
  const activeChat = chats.find((chat) => chat.id === activeChatId) ?? null;
  const hasHiddenChats = chats.length > COLLAPSED_CHAT_LIMIT;
  const visibleChats = isChatListExpanded ? chats : chats.slice(0, COLLAPSED_CHAT_LIMIT);
  async function loadChats({ silent = false }: { silent?: boolean } = {}) {
    const requestId = ++chatsRequestRef.current;
    setIsLoadingChats(true);
    loadingMoreRef.current = false;
    setIsLoadingMoreChats(false);
    try {
      const payload = await chatApi.listConversations();
      const list = payload.data ?? [];
      const preferredId = activeIdRef.current ?? window.localStorage.getItem(LAST_ACTIVE_CHAT_STORAGE_KEY);
      if (preferredId && !list.some((chat) => chat.id === preferredId)) {
        const preferred = await chatApi.getConversation(preferredId);
        if (preferred.data && !preferred.data.archived) list.push(preferred.data);
      }
      if (requestId !== chatsRequestRef.current) return;
      setChats(list);
      setNextChatsCursor(payload.pageInfo?.nextCursor ?? null);

      if (!activeIdRef.current) {
        const lastActiveId = window.localStorage.getItem(LAST_ACTIVE_CHAT_STORAGE_KEY);
        const preferred = lastActiveId ? list.find((chat) => chat.id === lastActiveId)?.id : null;
        const nextActiveId = preferred ?? list[0]?.id ?? null;
        if (!nextActiveId && lastActiveId) {
          window.localStorage.removeItem(LAST_ACTIVE_CHAT_STORAGE_KEY);
        }
        setActiveChatId((current) => current ?? nextActiveId);
      }
    } catch (loadError) {
      if (!silent && requestId === chatsRequestRef.current) setPageError(loadError instanceof Error ? loadError.message : t("chatApi.listConversationsFailed"));
    } finally {
      if (requestId === chatsRequestRef.current) setIsLoadingChats(false);
    }
  }

  async function loadMoreChats() {
    if (!nextChatsCursor || loadingMoreRef.current) return;
    const requestId = chatsRequestRef.current;
    loadingMoreRef.current = true;
    setIsLoadingMoreChats(true);
    try {
      const page = await chatApi.listConversations(nextChatsCursor);
      if (requestId !== chatsRequestRef.current) return;
      setChats((current) => [...current, ...page.data.filter((chat) => !current.some((item) => item.id === chat.id))]);
      setNextChatsCursor(page.pageInfo?.nextCursor ?? null);
      setIsChatListExpanded(true);
    } catch (error) {
      if (requestId === chatsRequestRef.current) setPageError(error instanceof Error ? error.message : t("conversationsHook.loadMoreFailed"));
    } finally {
      if (requestId === chatsRequestRef.current) {
        loadingMoreRef.current = false;
        setIsLoadingMoreChats(false);
      }
    }
  }

  async function createNewChat() {
    setIsCreatingChat(true);
    setPageError(null);
    try {
      await persistCurrentStreamingAssistantIfNeeded(activeChatId);

      const defaults = await loadAccountChatDefaults();
      const payload = await chatApi.createConversation("New Chat");
      const chat = payload.data;
      const seededPreferences: ChatScopedPreferences = {
        ...defaults.preferences,
      };

      window.localStorage.setItem(getChatPrefsStorageKey(chat.id), JSON.stringify(seededPreferences));
      applyChatPreferences(seededPreferences);

      setActiveChatId(chat.id);
      resetConversation();
      await loadChats();
    } catch (createError) {
      setPageError(createError instanceof Error ? createError.message : t("chatApi.createConversationFailed"));
    } finally {
      setIsCreatingChat(false);
    }
  }

  function startEditingChat(chat: ChatSummary) {
    setEditingChatId(chat.id);
    setEditingTitle(chat.title);
  }

  function cancelEditingChat() {
    setEditingChatId(null);
    setEditingTitle("");
  }

  async function saveEditedTitle(chatId: string) {
    const title = editingTitle.trim();
    if (!title) return;

    setPageError(null);
    try {
      await chatApi.renameConversation(chatId, title);
      setChats((prev) => prev.map((chat) => (chat.id === chatId ? { ...chat, title } : chat)));
      cancelEditingChat();
    } catch (renameError) {
      setPageError(renameError instanceof Error ? renameError.message : t("chatApi.renameConversationFailed"));
    }
  }

  async function performDeleteChat(chatId: string) {
    await chatApi.deleteConversation(chatId);
    chatsRequestRef.current += 1;
    loadingMoreRef.current = false;
    setIsLoadingMoreChats(false);
    const nextChats = chats.filter((chat) => chat.id !== chatId);
    setChats(nextChats);

    if (activeChatId === chatId) {
      const nextActiveId = nextChats[0]?.id ?? null;
      setActiveChatId(nextActiveId);
      if (!nextActiveId) {
        window.localStorage.removeItem(LAST_ACTIVE_CHAT_STORAGE_KEY);
        resetConversation();
      }
    }
  }

  async function ensureActiveChatId(titleSeed: string, shouldActivate?: () => boolean): Promise<string> {
    const normalizedSeed = titleSeed.replace(/\s+/g, " ").trim().slice(0, 40);

    async function maybeUpdateAutoGeneratedTitle(chatId: string, nextTitleSeed: string) {
      const nextTitle = nextTitleSeed.replace(/\s+/g, " ").trim();
      if (!nextTitle) return;

      const targetChat = chats.find((chat) => chat.id === chatId);
      if (targetChat && !isAutoGeneratedTitle(targetChat.title)) {
        return;
      }

      try {
        const payload = await chatApi.renameConversation(chatId, nextTitle);
        const updatedTitle = payload.data?.title ?? nextTitle;
        setChats((prev) => prev.map((chat) => (chat.id === chatId ? { ...chat, title: updatedTitle } : chat)));
      } catch {
        // Best effort: title update failure should not block sending.
      }
    }

    if (activeChatId) {
      await maybeUpdateAutoGeneratedTitle(activeChatId, normalizedSeed);
      return activeChatId;
    }

    const payload = await chatApi.createConversation(normalizedSeed || "New Chat");
    const chatId = payload.data.id;
    const seededPreferences: ChatScopedPreferences = {
      modelMode,
      selectedChatModel,
      selectedImageModel,
      selectedVideoModel,
      selectedManualTool: modelMode === "chat" ? selectedManualTool : "none",
      manualToolsOnly: modelMode === "chat" ? manualToolsOnly : false,
    };
    window.localStorage.setItem(getChatPrefsStorageKey(chatId), JSON.stringify(seededPreferences));
    if (!shouldActivate) {
      setActiveChatId(chatId);
    } else if (shouldActivate()) {
      setActiveChatId((current) => current === activeChatId ? chatId : current);
    }
    return chatId;
  }
  useEffect(() => {
    void loadChats();
    return () => { chatsRequestRef.current += 1; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  useEffect(() => {
    // Initial null means history has not loaded yet; preserve the saved selection.
    if (!activeChatId) return;
    window.localStorage.setItem(LAST_ACTIVE_CHAT_STORAGE_KEY, activeChatId);
  }, [activeChatId]);
  /**
   * Flipping the memory switch applies from the next message, and the list is
   * updated from the response rather than optimistically, so the header never
   * claims a state the server did not store.
   */
  async function toggleEphemeral(next: boolean) {
    const chat = chats.find((item) => item.id === activeChatId);
    if (!chat) return;
    setIsEphemeralSaving(true);
    try {
      await chatApi.setEphemeral(chat.id, next);
      await loadChats();
    } catch {
      await loadChats();
    } finally {
      setIsEphemeralSaving(false);
    }
  }

  /** The topics a conversation may draw on. Empty means every topic. */
  async function loadDocumentTopics() {
    try {
      const response = await fetch("/api/documents", { cache: "no-store" });
      if (!response.ok) return;
      const payload = await response.json();
      const topics = (Array.isArray(payload.data) ? payload.data : [])
        .map((document: { collection?: string | null }) => document.collection)
        .filter((value: unknown): value is string => typeof value === "string" && value.length > 0);
      setDocumentTopics([...new Set<string>(topics)].sort());
    } catch {
      // A conversation can still be created without a scope.
    }
  }

  async function setDocumentScope(next: string[]) {
    const chat = chats.find((item) => item.id === activeChatId);
    if (!chat) return;
    try {
      await chatApi.setDocumentScope(chat.id, next);
    } catch (scopeError) {
      // The toolbar asks for a scope without awaiting this, so a rejection would
      // be an unhandled one: the chips would quietly go on showing the scope the
      // change was meant to replace, with nothing saying the change did not take.
      setPageError(scopeError instanceof Error ? scopeError.message : t("chatApi.setDocumentScopeFailed"));
    } finally {
      // Once either way, and once: the list is what the chips read, so it has to
      // be the stored scope rather than the one that was asked for.
      await loadChats();
    }
  }

  return {
    toggleEphemeral, isEphemeralSaving, documentTopics, loadDocumentTopics, setDocumentScope,
    chats, activeChat, isLoadingChats, isCreatingChat, editingChatId, editingTitle, setEditingTitle, isChatListExpanded,
    setIsChatListExpanded, visibleChats, hasHiddenChats, loadChats, createNewChat, startEditingChat,
    cancelEditingChat, saveEditedTitle, performDeleteChat, ensureActiveChatId,
    nextChatsCursor, isLoadingMoreChats, loadMoreChats,
  };
}
