import { ChatSummary } from "@/features/chat/page-utils";
import type { Dispatch, SetStateAction } from "react";
import { useEffect, useState } from "react";
import { chatApi } from "@/features/chat/api-client";
import { getChatPrefsStorageKey } from "@/features/chat/preferences";
import type { ChatScopedPreferences } from "@/features/chat/types";
import { COLLAPSED_CHAT_LIMIT, LAST_ACTIVE_CHAT_STORAGE_KEY } from "@/features/chat/types";

type Options = {
  activeChatId: string | null;
  setActiveChatId: Dispatch<SetStateAction<string | null>>;
  preferences: ChatScopedPreferences;
  applyChatPreferences: (preferences: ChatScopedPreferences) => void;
  resetConversation: () => void;
  persistCurrentStreamingAssistantIfNeeded: (chatId: string | null) => Promise<void>;
  setPageError: Dispatch<SetStateAction<string | null>>;
};
function isAutoGeneratedTitle(title: string | null | undefined): boolean {
  const normalized = (title ?? "").replace(/\s+/g, " ").trim().toLowerCase();
  if (!normalized) return true;
  return normalized === "new chat" || normalized === "新会话" || normalized === "untitled";
}
export function useConversations({ activeChatId, setActiveChatId, preferences, applyChatPreferences, resetConversation, persistCurrentStreamingAssistantIfNeeded, setPageError }: Options) {
  const { modelMode, selectedChatModel, selectedImageModel, selectedVideoModel, selectedManualTool, manualToolsOnly } = preferences;
  const [chats, setChats] = useState<ChatSummary[]>([]);
  const [isCreatingChat, setIsCreatingChat] = useState(false);
  const [editingChatId, setEditingChatId] = useState<string | null>(null);
  const [editingTitle, setEditingTitle] = useState("");
  const [isChatListExpanded, setIsChatListExpanded] = useState(false);
  const activeChat = chats.find((chat) => chat.id === activeChatId) ?? null;
  const hasHiddenChats = chats.length > COLLAPSED_CHAT_LIMIT;
  const visibleChats = isChatListExpanded ? chats : chats.slice(0, COLLAPSED_CHAT_LIMIT);
  async function loadChats() {
    try {
      const payload = await chatApi.listConversations();
      const list = payload.data ?? [];
      setChats(list);

      if (!activeChatId) {
        const lastActiveId = window.localStorage.getItem(LAST_ACTIVE_CHAT_STORAGE_KEY);
        const preferred = lastActiveId ? list.find((chat) => chat.id === lastActiveId)?.id : null;
        const nextActiveId = preferred ?? list[0]?.id ?? null;
        if (!nextActiveId && lastActiveId) {
          window.localStorage.removeItem(LAST_ACTIVE_CHAT_STORAGE_KEY);
        }
        setActiveChatId((current) => current ?? nextActiveId);
      }
    } catch (loadError) {
      setPageError(loadError instanceof Error ? loadError.message : "读取会话列表失败");
    }
  }

  async function createNewChat() {
    setIsCreatingChat(true);
    setPageError(null);
    try {
      await persistCurrentStreamingAssistantIfNeeded(activeChatId);

      const payload = await chatApi.createConversation("New Chat");
      const chat = payload.data;
      const seededPreferences: ChatScopedPreferences = {
        modelMode,
        selectedChatModel,
        selectedImageModel,
        selectedVideoModel,
        selectedManualTool: modelMode === "chat" ? selectedManualTool : "none",
        manualToolsOnly: modelMode === "chat" ? manualToolsOnly : false,
      };

      window.localStorage.setItem(getChatPrefsStorageKey(chat.id), JSON.stringify(seededPreferences));
      applyChatPreferences(seededPreferences);

      setActiveChatId(chat.id);
      resetConversation();
      await loadChats();
    } catch (createError) {
      setPageError(createError instanceof Error ? createError.message : "创建会话失败");
    } finally {
      setIsCreatingChat(false);
    }
  }

  function startEditingChat(chat: ChatSummary) {
    setEditingChatId(chat.id);
    setEditingTitle(chat.title);
  }

  function cancelEditingChat() {
    setEditingChatId(null);
    setEditingTitle("");
  }

  async function saveEditedTitle(chatId: string) {
    const title = editingTitle.trim();
    if (!title) return;

    setPageError(null);
    try {
      await chatApi.renameConversation(chatId, title);
      setChats((prev) => prev.map((chat) => (chat.id === chatId ? { ...chat, title } : chat)));
      cancelEditingChat();
    } catch (renameError) {
      setPageError(renameError instanceof Error ? renameError.message : "重命名会话失败");
    }
  }

  async function performDeleteChat(chatId: string) {
    await chatApi.deleteConversation(chatId);
    const nextChats = chats.filter((chat) => chat.id !== chatId);
    setChats(nextChats);

    if (activeChatId === chatId) {
      const nextActiveId = nextChats[0]?.id ?? null;
      setActiveChatId(nextActiveId);
      if (!nextActiveId) {
        window.localStorage.removeItem(LAST_ACTIVE_CHAT_STORAGE_KEY);
        resetConversation();
      }
    }
  }

  async function ensureActiveChatId(titleSeed: string): Promise<string> {
    const normalizedSeed = titleSeed.replace(/\s+/g, " ").trim().slice(0, 40);

    async function maybeUpdateAutoGeneratedTitle(chatId: string, nextTitleSeed: string) {
      const nextTitle = nextTitleSeed.replace(/\s+/g, " ").trim();
      if (!nextTitle) return;

      const targetChat = chats.find((chat) => chat.id === chatId);
      if (targetChat && !isAutoGeneratedTitle(targetChat.title)) {
        return;
      }

      try {
        const payload = await chatApi.renameConversation(chatId, nextTitle);
        const updatedTitle = payload.data?.title ?? nextTitle;
        setChats((prev) => prev.map((chat) => (chat.id === chatId ? { ...chat, title: updatedTitle } : chat)));
      } catch {
        // Best effort: title update failure should not block sending.
      }
    }

    if (activeChatId) {
      await maybeUpdateAutoGeneratedTitle(activeChatId, normalizedSeed);
      return activeChatId;
    }

    const payload = await chatApi.createConversation(normalizedSeed || "New Chat");
    const chatId = payload.data.id;
    const seededPreferences: ChatScopedPreferences = {
      modelMode,
      selectedChatModel,
      selectedImageModel,
      selectedVideoModel,
      selectedManualTool: modelMode === "chat" ? selectedManualTool : "none",
      manualToolsOnly: modelMode === "chat" ? manualToolsOnly : false,
    };
    window.localStorage.setItem(getChatPrefsStorageKey(chatId), JSON.stringify(seededPreferences));
    setActiveChatId(chatId);
    return chatId;
  }
  useEffect(() => {
    void loadChats();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  useEffect(() => {
    // Initial null means history has not loaded yet; preserve the saved selection.
    if (!activeChatId) return;
    window.localStorage.setItem(LAST_ACTIVE_CHAT_STORAGE_KEY, activeChatId);
  }, [activeChatId]);
  return {
    chats, activeChat, isCreatingChat, editingChatId, editingTitle, setEditingTitle, isChatListExpanded,
    setIsChatListExpanded, visibleChats, hasHiddenChats, loadChats, createNewChat, startEditingChat,
    cancelEditingChat, saveEditedTitle, performDeleteChat, ensureActiveChatId,
  };
}

