import { test as base, expect, type Page } from "@playwright/test";
import { mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { startStandaloneServer } from "../helpers/standalone-server";
import { openWorkspace } from "../helpers/workspace-entry";
import { configureOfflineModels } from "../helpers/model-fixture";
const test = base.extend<{ app: Awaited<ReturnType<typeof startStandaloneServer>> }>({
  app: async ({}, runTest) => { const app = await startStandaloneServer({ modelFixture: true }); try { await runTest(app); } finally { await app.close(); } },
});
async function upload(page: Page, filename: string, text: string) {
  await page.getByLabel("选择知识文档").setInputFiles({ name: filename, mimeType: "text/plain", buffer: Buffer.from(text) });
  const response = page.waitForResponse(response => response.url().endsWith("/api/documents") && response.request().method() === "POST");
  await page.getByRole("button", { name: "导入文档", exact: true }).click();
  const result = await response; expect(result.ok(), await result.text()).toBe(true);
  await expect(page.getByRole("button", { name: "导入文档", exact: true })).toBeEnabled();
  return (await result.json()).data.document;
}
test("local search explains scope and old chat citations distinguish changed and deleted sources", async ({ page, app }) => {
  const errors: string[] = []; page.on("pageerror", error => errors.push(error.message));
  await openWorkspace(page, app.origin);
  await page.goto(`${app.origin}/knowledge`);
  await page.getByLabel("所属主题（可选）").fill("Manual|操作");
  const original = await upload(page, "星河手册.txt", "星河回滚窗口为三十分钟。\n\n备用线路每月巡检。");
  await page.getByLabel("所属主题（可选）").fill("Support");
  await upload(page, "客服说明.txt", "客服团队每天上午九点到下午六点值班。");
  await page.getByLabel("检索资料集合").selectOption("Support");
  await page.getByLabel("检索文档", { exact: true }).fill("星河回滚窗口");
  await page.getByRole("button", { name: "检索文档", exact: true }).click();
  await expect(page.getByText("没有匹配的文档片段，请尝试文档中的关键词。", { exact: true })).toBeVisible();
  await page.getByLabel("检索资料集合").selectOption("Manual|操作");
  await page.getByRole("button", { name: "检索文档", exact: true }).click();
  await expect(page.getByText(/本地关键词检索 · 集合：Manual/)).toHaveCount(2);
  await expect(page.getByText("引用版本一致（已核对）", { exact: true })).toHaveCount(2);
  expect(app.providerCalls).toHaveLength(0);
  await configureOfflineModels(page, { chat: "anthropic/claude-opus-4.6" });
  await page.goto(`${app.origin}/chat`);
  await page.getByRole("checkbox").check();
  await page.getByPlaceholder(/输入你的问题/).fill("星河回滚窗口是多少");
  await page.getByRole("button", { name: "发送", exact: true }).click();
  const source = page.getByRole("link", { name: "星河手册.txt · 片段 1", exact: true });
  await expect(source).toBeVisible();
  await expect(source.locator("..").getByText("引用版本一致（已核对）", { exact: true })).toBeVisible();
  const chatUrl = page.url();
  await page.goto(`${app.origin}/knowledge`);
  await page.getByLabel("所属主题（可选）").fill("Manual|操作");
  const changed = await upload(page, "星河手册.txt", "星河回滚窗口为三十分钟。\n\n备用线路每天巡检。");
  expect(changed.id).toBe(original.id);
  await page.goto(chatUrl);
  await expect(source).toBeVisible();
  await expect(source.locator("..").getByText("资料已更新：下方保留回答时的摘录，链接展示当前资料。", { exact: true })).toBeVisible();
  const dir = join(tmpdir(), "ria-citation-version-qa"); await mkdir(dir, { recursive: true });
  const evidence = page.locator("article details").filter({ hasText: "资料已更新" }).first();
  await evidence.screenshot({ path: join(dir, "desktop.png"), animations: "disabled" });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await evidence.screenshot({ path: join(dir, "mobile.png"), animations: "disabled" });
  await source.click();
  await expect(page.getByText(/资料版本或原引用片段已变化/)).toBeVisible();
  await expect(page.getByText("备用线路每天巡检。", { exact: true })).toBeVisible();
  await page.getByRole("link", { name: "返回知识库", exact: true }).click();
  await page.getByLabel("检索资料集合").selectOption("Manual|操作");
  page.once("dialog", dialog => dialog.accept());
  await page.getByLabel("删除文档 星河手册.txt").click();
  await expect(page.getByText("文档及索引已删除。", { exact: true })).toBeVisible();
  await expect(page.getByLabel("检索资料集合")).toHaveValue("Manual|操作");
  await expect(page.getByLabel("检索资料集合").locator('option:checked')).toHaveText("Manual|操作（暂无资料）");
  await page.goto(chatUrl);
  await expect(source.locator("..").getByText("资料已删除：下方仅为历史摘录，原文已不可访问。", { exact: true })).toBeVisible();
  await expect(page.locator("article").getByText("星河回滚窗口为三十分钟。", { exact: true })).toBeVisible();
  await app.restart(); await page.reload();
  await expect(source.locator("..").getByText("资料已删除：下方仅为历史摘录，原文已不可访问。", { exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});
