import { NextRequest } from "next/server";
import { z } from "zod";
import { requireRequestUser } from "@/lib/auth/request-user";
import { decodePersistedUserMessage, truncateTitle } from "@/lib/ai/ui-message";
import { ApiError, createApiErrorResponse, normalizeApiError } from "@/lib/server/api-error";
import { getChat, listChatMessages, saveChatMessage, updateChatTitle } from "@/lib/chat/store";
import { readJsonBody } from "@/lib/server/request-body";

const createMessageSchema = z.strictObject({
  role: z.enum(["user", "assistant", "system"]),
  content: z.string().min(1).max(1_000_000),
  clientMessageId: z.string().trim().min(1).max(200).regex(/^[a-zA-Z0-9_-]+$/).optional(),
  status: z.enum(["pending", "success", "error"]).optional(),
});

type Params = {
  params: Promise<{ id: string }>;
};

function isAutoGeneratedTitle(title: string): boolean {
  const normalized = title.replace(/\s+/g, " ").trim().toLowerCase();
  if (!normalized) return true;
  return normalized === "new chat" || normalized === "新会话" || normalized === "untitled";
}

export async function GET(req: NextRequest, context: Params) {
  try {
    const user = await requireRequestUser(req);
    const { id: chatId } = await context.params;

    const messages = await listChatMessages(user.id, chatId);
    if (!messages) {
      throw new ApiError({ code: "NOT_FOUND", message: "Conversation not found" });
    }

    return Response.json({ data: messages });
  } catch (error) {
    console.error("/api/conversations/[id]/messages GET error", normalizeApiError(error).code);
    return createApiErrorResponse(error, "Failed to fetch messages");
  }
}

export async function POST(req: NextRequest, context: Params) {
  try {
    const user = await requireRequestUser(req);
    const { id: chatId } = await context.params;
    const parsed = createMessageSchema.safeParse(await readJsonBody(req));
    if (!parsed.success) throw parsed.error;
    const chat = await getChat(user.id, chatId);
    if (!chat) {
      throw new ApiError({ code: "NOT_FOUND", message: "Conversation not found" });
    }

    const message = await saveChatMessage({
      chatId: chat.id,
      role: parsed.data.role,
      content: parsed.data.content,
      clientMessageId: parsed.data.clientMessageId,
      status: parsed.data.status ?? "success",
    });

    if (parsed.data.role === "user" && isAutoGeneratedTitle(chat.title)) {
      const parsedUser = decodePersistedUserMessage(parsed.data.content);
      const titleSeed = (parsedUser?.text ?? parsed.data.content).trim();
      if (titleSeed) {
        await updateChatTitle(user.id, chat.id, truncateTitle(titleSeed));
      }
    }

    return Response.json({ data: message }, { status: 201 });
  } catch (error) {
    console.error("/api/conversations/[id]/messages POST error", normalizeApiError(error).code);
    return createApiErrorResponse(error, "Failed to create message");
  }
}
